### ISSUE TITLE
Using external data/TimeSeries - Expected Data type?

### ISSUE THREAD

**Issue by ddofer** [cesium-ml/cesium-data#1]
I saw the library and wanted to try it on my own timeseries data. 
I tried loading in a dataset with pandas where the time column was parsed as datetime64 and got an error when trying to use cesium on it. The existing EEG example is a custom dataset, and from the docs it seems you have your own datatype, based on parsing from the file? 
Is there any chance of providing an example for using external data with the tool and what format is expected? 
Thanks!

**Comment by bnaul** [comment]
This repository is just a mirror of raw data from other sources; the `cesium.datasets` module contains code that downloads and ingests it (see, e.g., https://github.com/cesium-ml/cesium/blob/master/cesium/datasets/andrzejak.py).

The time column is currently expected to be a float, but I agree that a datetime should be accepted as well. I can easily make that change in `cesium` but for now if you just call `.astype(float)` on your `datetime64` column then it should work just fine.

Closing and replacing with cesium-ml/cesium#258.
